name: Auto Pull Request to Upstream

on:
  push:
    branches:
      - main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "heekyung.kim@tridge.com"
          git config --global user.name "Heekyung Kim"

      - name: Create Pull Request to Fork
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main  # The base branch in the fork (gimgit/AI-1-gimgit main branch).
          branch: main  # Your original repo's branch (origin main branch).
          push-to-fork: gimgit/AI-1-gimgit  # The forked repository where the PR will be created.
          title: "Auto PR: Sync changes from origin to fork"
          body: "This PR was automatically created to sync changes from the origin repository."