name: Auto Pull Request to Upstream

on:
  push:
    branches:
      - main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "abcd@example.com"
          git config --global user.name "gimgit"

      - name: Create Pull Request to Upstream
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main  # Base branch of the original repository
          head: gimgit:main  # Your fork's branch
          title: "Auto PR: Sync changes from copied repository"
          body: "This PR was automatically created to sync changes from my fork to the upstream repository."
